
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_SOCIALNETWORK_USERDATA_SUCCESS = 'USER_SOCIALNETWORK_USERDATA_SUCCESS'